version: 0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    steps:
      - clone

      - cache_restore:
          path: node_modules
          key: 'npm-{{ hash "package-lock.json" }}-v1'

      - run: wget -qO- https://api.wodby.com/v1/get/cli | sh
      - run: wodby ci init $WODBY_BUILD_ID

      - run: wodby ci run -s nextjs -- npm i
      - cache_save:
          key: 'npm-{{ hash "package-lock.json" }}-v1'
          path: node_modules

      - run: wodby ci build nextjs
      - run: wodby ci release
      - run: wodby ci deploy
